Repository pknu-wap/GgooMeme, pull requests merged in 2024-05, with the labels that each got.

#26 2-4차 릴리즈
  Ggoememe-Backend/src/main/resources/data.sql
Labels: release

#27 Frontend
  .idea/workspace.xml
  Ggoememe-Backend/.gitignore
  Ggoememe-Backend/build.gradle
  Ggoememe-Backend/src/main/resources/application.properties
  GgooMeme_Frontend/react-social/src/app/App.js
  GgooMeme_Frontend/react-social/src/common/AppHeader.js
  GgooMeme_Frontend/react-social/src/home/MainList.css
  GgooMeme_Frontend/react-social/src/home/MainList.js
  GgooMeme_Frontend/react-social/src/user/login/Login.css
  GgooMeme_Frontend/react-social/src/user/login/Login.js
  GgooMeme_Frontend/react-social/src/user/profile/Profile.js
  README.md
Labels: develop

#34 Develop - Cors 수정
  Ggoememe-Backend/src/main/resources/application.properties
  GgooMeme_Frontend/react-social/src/app/App.js
  GgooMeme_Frontend/react-social/src/constants/index.js
  GgooMeme_Frontend/react-social/src/home/Home.css
  GgooMeme_Frontend/react-social/src/home/Home.js
  GgooMeme_Frontend/react-social/src/home/MainList.css
  GgooMeme_Frontend/react-social/src/home/MainList.js
  GgooMeme_Frontend/react-social/src/home/Order.css
  GgooMeme_Frontend/react-social/src/home/Order.js
Labels: release

#38 #33-hastag->tag
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/PostController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/Post.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/PostDto.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/PostPreviewDto.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/service/PostService.java
  Ggoememe-Backend/src/main/resources/data.sql
Labels: develop

#40 feature/#32-메인페이지정렬
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/PostController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/Post.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/service/PostService.java
  Ggoememe-Backend/src/main/resources/data.sql
Labels: develop, feature

#51 Fix/#50 bugfix
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/service/PostService.java
Labels: develop, fix
