Repository pknu-wap/GgooMeme, pull requests merged in 2024-04, with the labels that each got.

#10 Feature/#7 post
  Ggoememe-Backend/build.gradle
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/config/SecurityConfig.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/PostController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/Hashtag.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/Post.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/User.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/PostDto.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/PostDtos.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/PostPreviewDto.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/PostPreviewDtos.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/response/post/RelatedPostResponse.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/repository/PostRepository.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/repository/QueryDSLRepository.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/service/PostService.java
  Ggoememe-Backend/src/main/resources/data.sql
Labels: develop

#12 feature/#11-KakaoLogin
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/AuthProvider.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/security/oauth2/user/KakaoOAuth2UserInfo.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/security/oauth2/user/OAuth2UserInfoFactory.java
Labels: develop

#18 Revert "Feature/#15 reply"
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/PostController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/ReplyController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/Post.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/domain/Reply.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/request/reply/ReplyRequest.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/response/reply/ReplyResponse.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/repository/ReplyRepository.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/service/ReplyService.java
  Ggoememe-Backend/src/main/resources/data.sql
Labels: fix

#22 2-1차 릴리즈
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/AuthController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/PostController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/ReplyController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/UserController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/service/MyPageService.java
Labels: release

#23 2-2차 릴리즈
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/controller/UserController.java
  Ggoememe-Backend/src/main/java/com/wap/GgoememeBackend/payload/MyPageDto.java
Labels: develop
